//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetManager
{
    using System;
    
    public enum RecursionInterval : int
    {
        None = 0,
        Monthly = 1,
        Weekly = 2,
        Annually = 3
    }
}
