//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public double Value { get; set; }
        public System.DateTime Date { get; set; }
        public string Desc { get; set; }
        public int UserId { get; set; }
        public Nullable<TransactionType> TrType { get; set; }
        public RecursionInterval RecursionType { get; set; }
        public int CatTransId { get; set; }
    
        public virtual User User { get; set; }
        public virtual CatTrans CatTran { get; set; }
    }
}
